packages:
  - 'apps/*'
  - 'packages/*'
  - 'scripts/*'

allowBuilds:
  '@nestjs/core': true
  '@parcel/watcher': true
  '@scarf/scarf': true
  '@swc/core': true
  argon2: true
  chromedriver: true
  cpu-features: true
  esbuild: true
  msgpackr-extract: true
  nx: true
  protobufjs: true
  puppeteer: true
  sharp: true
  ssh2: true
  unrs-resolver: true

overrides:
  qs: '>=6.14.1'
  zod: 4.1.13
  fast-xml-parser: 5.11.1
  axios: '>=1.13.5'
  punycode: ^2.3.1
  minimatch: '>=10.2.3'
  '@eslint/eslintrc>minimatch': 3.1.5
  koa: '>=3.1.2'
  basic-ftp: '>=5.2.0'
  rollup: '>=4.59.0'
  serialize-javascript: '>=7.0.3'
  flatted: '>=3.4.2'
  drizzle-orm: 0.45.2
  multer: '>=2.1.1'
  immutable: '>=5.1.8'
  svgo: '>=3.3.3'
  undici: 6.24.0
  node-forge: '>=1.4.0'
  prosemirror-model: 1.25.11
  'express@4>path-to-regexp': 0.1.13
  '@nestjs/core>path-to-regexp': 8.4.0
  '@nestjs/platform-express>path-to-regexp': 8.4.0
  '@nestjs/swagger>path-to-regexp': 8.4.0
  'router>path-to-regexp': 8.4.0
  'picomatch@<2.3.2': 2.3.2
  'picomatch@>=4.0.0 <4.0.4': 4.0.4
  nx: 23.2.0
  '@nx/devkit': 23.2.0
  '@nx/eslint': 23.2.0
  '@nx/eslint-plugin': 23.2.0
  '@nx/jest': 23.2.0
  '@nx/js': 23.2.0
  '@nx/next': 23.2.0
  '@nx/node': 23.2.0
  '@nx/playwright': 23.2.0
  '@nx/react': 23.2.0
  '@nx/web': 23.2.0
  '@nx/webpack': 23.2.0
