import type { IStorageConfig, StorageEnvironmentVariableNames } from './interfaces';

export const DEFAULT_SIGNED_URL_EXPIRES_IN_SECONDS = 900;
export const MAX_SIGNED_URL_EXPIRES_IN_SECONDS = 604800;

export const DEFAULT_STORAGE_ENV_VAR_NAMES: Required<StorageEnvironmentVariableNames> = {
  STORAGE_INSTANCES: 'STORAGE_INSTANCES',
  STORAGE_DEFAULT_INSTANCE: 'STORAGE_DEFAULT_INSTANCE',
  STORAGE_PROVIDER: 'STORAGE_PROVIDER',
  STORAGE_DEFAULT_BUCKET: 'STORAGE_DEFAULT_BUCKET',
  STORAGE_S3_ENDPOINT: 'STORAGE_S3_ENDPOINT',
  STORAGE_S3_REGION: 'STORAGE_S3_REGION',
  STORAGE_S3_ACCESS_KEY_ID: 'STORAGE_S3_ACCESS_KEY_ID',
  STORAGE_S3_SECRET_ACCESS_KEY: 'STORAGE_S3_SECRET_ACCESS_KEY',
  STORAGE_S3_SESSION_TOKEN: 'STORAGE_S3_SESSION_TOKEN',
  STORAGE_S3_FORCE_PATH_STYLE: 'STORAGE_S3_FORCE_PATH_STYLE',
  STORAGE_S3_BUCKET: 'STORAGE_S3_BUCKET',
  STORAGE_S3_PUBLIC_BASE_URL: 'STORAGE_S3_PUBLIC_BASE_URL',
  STORAGE_S3_SIGNED_URL_EXPIRES_IN_SECONDS: 'STORAGE_S3_SIGNED_URL_EXPIRES_IN_SECONDS',
  STORAGE_TEST_MODE: 'STORAGE_TEST_MODE'
};

export const DEFAULT_STORAGE_CONFIG: Readonly<
  Required<Pick<IStorageConfig, 'provider' | 'testMode'>> & {
    s3: {
      forcePathStyle: boolean;
      signedUrlExpiresInSeconds: number;
    };
  }
> = {
  provider: 's3',
  testMode: false,
  s3: {
    forcePathStyle: false,
    signedUrlExpiresInSeconds: DEFAULT_SIGNED_URL_EXPIRES_IN_SECONDS
  }
};
