/**
 * @fileoverview Database migration runner for the main application database.
 *
 * This module provides programmatic migration execution using Drizzle ORM's
 * built-in migrator. It handles migration file discovery and ensures isolation
 * from other database packages in the monorepo.
 *
 * ## Migration Strategy
 *
 * Drizzle ORM uses a **forward-only migration pattern**:
 * - Migrations are SQL files generated by `drizzle-kit generate`
 * - Each migration runs exactly once and is tracked in a migrations table
 * - There is no built-in rollback mechanism
 *
 * ## Rollback Approach
 *
 * To "undo" a migration, create a **compensating migration**:
 * 1. Identify the changes that need reversal
 * 2. Write SQL to reverse those changes (e.g., drop added columns)
 * 3. Generate a new migration with `pnpm run db:generate`
 * 4. Apply with `pnpm run db:migrate`
 *
 * @example Compensating migration pattern
 * ```sql
 * -- 0001_add_feature_flag.sql (original)
 * ALTER TABLE users ADD COLUMN feature_flag BOOLEAN DEFAULT false;
 *
 * -- 0002_revert_feature_flag.sql (compensating)
 * ALTER TABLE users DROP COLUMN feature_flag;
 * ```
 *
 * ## Multi-Package Isolation
 *
 * Each database package (`db-core`, `db-outbox`) uses a unique migrations
 * table to prevent conflicts. This allows running migrations from different
 * packages on the same database without interference.
 *
 * @module @package/db-core/migrations
 * @see {@link ./constants.ts} For migration table configuration
 * @see {@link https://orm.drizzle.team/docs/migrations | Drizzle Migrations}
 *
 * @example Running migrations programmatically
 * ```typescript
 * import { runMigrations } from '@package/db-core/migrations/runner';
 *
 * await runMigrations(process.env.DATABASE_URL);
 * ```
 *
 * @example Running migrations via CLI
 * ```bash
 * # Generate migrations from schema changes
 * pnpm run db:generate
 *
 * # Apply pending migrations
 * pnpm run db:migrate
 * ```
 */

import { existsSync } from 'node:fs';
import { join, resolve } from 'node:path';

import { drizzle } from 'drizzle-orm/node-postgres';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
import { Pool } from 'pg';

import * as schema from '../schema';
import { MIGRATIONS_TABLE } from './constants';

// Re-export constants for external use
export { MIGRATIONS_TABLE, MIGRATIONS_SCHEMA } from './constants';

/**
 * Resolves the path to the migrations folder.
 *
 * Uses `__dirname` to locate the `drizzle/` folder relative to this module,
 * ensuring correct resolution regardless of the process's working directory.
 * Falls back to `process.cwd()` if the relative path doesn't exist.
 *
 * @returns Absolute path to the migrations folder
 * @internal
 */
const getMigrationsFolder = (): string => {
  // Get the directory of this file using __dirname (CommonJS)
  const currentDir = __dirname;

  // Navigate from packages/db-core/src/migrations/ to packages/db-core/drizzle
  const migrationsPath = resolve(currentDir, '..', '..', 'drizzle');

  // Fallback: if the relative path doesn't exist, try from process.cwd()
  if (!existsSync(migrationsPath)) {
    const cwdPath = join(process.cwd(), 'packages', 'db-core', 'drizzle');
    if (existsSync(cwdPath)) {
      return cwdPath;
    }
  }

  return migrationsPath;
};

/**
 * Executes all pending database migrations for the main database.
 *
 * This function:
 * 1. Creates a new database connection pool
 * 2. Locates migration files in the `drizzle/` folder
 * 3. Applies any migrations not yet recorded in the migrations table
 * 4. Closes the connection pool
 *
 * Migrations are tracked in a package-specific table (`__drizzle_migrations_main`)
 * to prevent conflicts with other database packages (e.g., `db-outbox`).
 *
 * @param databaseUrl - PostgreSQL connection string (e.g., `postgres://user:pass@host:5432/db`)
 * @throws Error if migration files cannot be found or migration execution fails
 *
 * @example Basic usage
 * ```typescript
 * import { runMigrations } from '@package/db-core/migrations/runner';
 *
 * // Run migrations on startup
 * await runMigrations(process.env.DATABASE_URL!);
 * ```
 *
 * @example With Testcontainers
 * ```typescript
 * import { PostgreSqlContainer } from '@testcontainers/postgresql';
 * import { runMigrations } from '@package/db-core/migrations/runner';
 *
 * const container = await new PostgreSqlContainer().start();
 * await runMigrations(container.getConnectionUri());
 * ```
 *
 * @example In application bootstrap
 * ```typescript
 * async function bootstrap() {
 *   // Apply migrations before starting the application
 *   if (process.env.RUN_MIGRATIONS === 'true') {
 *     await runMigrations(process.env.DATABASE_URL!);
 *   }
 *
 *   // Start NestJS application
 *   const app = await NestFactory.create(AppModule);
 *   await app.listen(3000);
 * }
 * ```
 */
export async function runMigrations(databaseUrl: string): Promise<void> {
  const pool = new Pool({ connectionString: databaseUrl });
  const db = drizzle(pool, { schema });

  try {
    const migrationsFolder = getMigrationsFolder();

    // eslint-disable-next-line no-console
    console.log(`Running migrations from: ${migrationsFolder}`);

    // Use the package-specific migrations table to prevent conflicts
    // with other database packages (e.g., db-outbox)
    await migrate(db, {
      migrationsFolder,
      migrationsTable: MIGRATIONS_TABLE
    });

    // eslint-disable-next-line no-console
    console.log('Migrations completed');
  } finally {
    await pool.end();
  }
}
