/**
 * Errors Factory Class
 *
 * AUTO-GENERATED by generate-factories.ts
 * DO NOT EDIT MANUALLY
 *
 * This file provides type-safe factory methods for creating
 * RegisteredError instances with autocomplete support.
 *
 * @example
 * ```ts
 * import { Errors } from '@package/errors';
 * throw Errors.userNotFound({ userId: '123' });
 * ```
 */

import { RegisteredError } from './registered-error.exception';

/**
 * Type-safe factory class for creating RegisteredError instances
 *
 * This class provides a factory method for each error code in the
 * registry with full type safety for parameters.
 *
 * @example
 * ```ts
 * throw Errors.userNotFound({ userId: '123' });
 * throw Errors.authInvalidCredentials();
 * throw Errors.validationFailed({ field: 'email' }, { requestId: 'abc' });
 * ```
 */
export class Errors {
  // Prevent instantiation
  private constructor() {}

  /**
   * Factory for AUTH_001: Invalid email or password
   *
   * No parameters required
   *
   * @example
   * ```ts
   * throw Errors.authinvalidEmailOr001({});
   * ```
   */
  static authinvalidEmailOr001(
    parameters: Record<string, never>,
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('AUTH_001', parameters, metadata);
  }

  /**
   * Factory for AUTH_002: Authentication token is missing
   *
   * No parameters required
   *
   * @example
   * ```ts
   * throw Errors.authauthenticationTokenIs002({});
   * ```
   */
  static authauthenticationTokenIs002(
    parameters: Record<string, never>,
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('AUTH_002', parameters, metadata);
  }

  /**
   * Factory for AUTH_003: Authentication token is invalid or expired
   *
   * No parameters required
   *
   * @example
   * ```ts
   * throw Errors.authauthenticationTokenIs003({});
   * ```
   */
  static authauthenticationTokenIs003(
    parameters: Record<string, never>,
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('AUTH_003', parameters, metadata);
  }

  /**
   * Factory for AUTH_004: Insufficient permissions: {$requiredPermission} required
   *
   * @param parameters.requiredPermission - Required permission (optional)
   *
   * @example
   * ```ts
   * throw Errors.authinsufficientPermissionsRequiredpermission004({});
   * ```
   */
  static authinsufficientPermissionsRequiredpermission004(
    parameters: Partial<{
      requiredPermission?: string;
    }>,
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('AUTH_004', parameters, metadata);
  }

  /**
   * Factory for AUTH_005: Invalid 2FA code provided
   *
   * No parameters required
   *
   * @example
   * ```ts
   * throw Errors.authinvalid2faCode005({});
   * ```
   */
  static authinvalid2faCode005(
    parameters: Record<string, never>,
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('AUTH_005', parameters, metadata);
  }

  /**
   * Factory for AUTH_006: Too many failed login attempts. Account locked for {$lockoutMinutes} minutes
   *
   * @param parameters.lockoutMinutes - Lockout duration
   *
   * @example
   * ```ts
   * throw Errors.authtooManyFailed006({ lockoutMinutes: 123 });
   * ```
   */
  static authtooManyFailed006(
    parameters: {
      lockoutMinutes: number;
    },
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('AUTH_006', parameters, metadata);
  }

  /**
   * Factory for AUTH_007: Password reset token is invalid or expired
   *
   * No parameters required
   *
   * @example
   * ```ts
   * throw Errors.authpasswordResetToken007({});
   * ```
   */
  static authpasswordResetToken007(
    parameters: Record<string, never>,
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('AUTH_007', parameters, metadata);
  }

  /**
   * Factory for AUTH_008: Session expired. Please login again
   *
   * No parameters required
   *
   * @example
   * ```ts
   * throw Errors.authsessionExpiredPlease008({});
   * ```
   */
  static authsessionExpiredPlease008(
    parameters: Record<string, never>,
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('AUTH_008', parameters, metadata);
  }

  /**
   * Factory for AUTH_009: Access denied from location: {$country}
   *
   * @param parameters.country - Country code (optional)
   *
   * @example
   * ```ts
   * throw Errors.authaccessDeniedFrom009({});
   * ```
   */
  static authaccessDeniedFrom009(
    parameters: Partial<{
      country?: string;
    }>,
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('AUTH_009', parameters, metadata);
  }

  /**
   * Factory for AUTH_010: Invalid role assignment: user cannot have role {$role}
   *
   * @param parameters.role - Invalid role
   *
   * @example
   * ```ts
   * throw Errors.authinvalidRoleAssignment010({ role: 'example' });
   * ```
   */
  static authinvalidRoleAssignment010(
    parameters: {
      role: string;
    },
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('AUTH_010', parameters, metadata);
  }

  /**
   * Factory for BIZ_001: Operation not allowed: {$reason}
   *
   * @param parameters.reason - Reason for disallow
   *
   * @example
   * ```ts
   * throw Errors.businessoperationNotAllowed001({ reason: 'example' });
   * ```
   */
  static businessoperationNotAllowed001(
    parameters: {
      reason: string;
    },
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('BIZ_001', parameters, metadata);
  }

  /**
   * Factory for BIZ_002: Cannot modify {$entity} in {$status} status
   *
   * @param parameters.entity - Entity type
   * @param parameters.status - Current status
   *
   * @example
   * ```ts
   * throw Errors.businesscannotModifyEntity002({ entity: 'example', status: 'example' });
   * ```
   */
  static businesscannotModifyEntity002(
    parameters: {
      entity: string;
      status: string;
    },
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('BIZ_002', parameters, metadata);
  }

  /**
   * Factory for BIZ_003: Insufficient balance: required {$required}, available {$available}
   *
   * @param parameters.required - Required amount
   * @param parameters.available - Available amount
   *
   * @example
   * ```ts
   * throw Errors.businessinsufficientBalanceRequired003({ required: 123, available: 123 });
   * ```
   */
  static businessinsufficientBalanceRequired003(
    parameters: {
      required: number;
      available: number;
    },
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('BIZ_003', parameters, metadata);
  }

  /**
   * Factory for BIZ_004: Resource is already {$action}
   *
   * @param parameters.action - Action (e.g., approved, cancelled)
   *
   * @example
   * ```ts
   * throw Errors.businessresourceIsAlready004({ action: 'example' });
   * ```
   */
  static businessresourceIsAlready004(
    parameters: {
      action: string;
    },
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('BIZ_004', parameters, metadata);
  }

  /**
   * Factory for BIZ_005: Maximum limit of {$limit} {$entity} reached
   *
   * @param parameters.limit - Maximum limit
   * @param parameters.entity - Entity type
   *
   * @example
   * ```ts
   * throw Errors.businessmaximumLimitOf005({ limit: 123, entity: 'example' });
   * ```
   */
  static businessmaximumLimitOf005(
    parameters: {
      limit: number;
      entity: string;
    },
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('BIZ_005', parameters, metadata);
  }

  /**
   * Factory for BIZ_006: Subscription is required for this feature
   *
   * No parameters required
   *
   * @example
   * ```ts
   * throw Errors.businesssubscriptionIsRequired006({});
   * ```
   */
  static businesssubscriptionIsRequired006(
    parameters: Record<string, never>,
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('BIZ_006', parameters, metadata);
  }

  /**
   * Factory for BIZ_007: Trial period has expired
   *
   * No parameters required
   *
   * @example
   * ```ts
   * throw Errors.businesstrialPeriodHas007({});
   * ```
   */
  static businesstrialPeriodHas007(
    parameters: Record<string, never>,
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('BIZ_007', parameters, metadata);
  }

  /**
   * Factory for BIZ_008: Invalid workflow transition from {$currentStatus} to {$newStatus}
   *
   * @param parameters.currentStatus - Current status
   * @param parameters.newStatus - Target status
   *
   * @example
   * ```ts
   * throw Errors.businessinvalidWorkflowTransition008({ currentStatus: 'example', newStatus: 'example' });
   * ```
   */
  static businessinvalidWorkflowTransition008(
    parameters: {
      currentStatus: string;
      newStatus: string;
    },
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('BIZ_008', parameters, metadata);
  }

  /**
   * Factory for DB_001: Failed to connect to database
   *
   * No parameters required
   *
   * @example
   * ```ts
   * throw Errors.databasefailedToConnect001({});
   * ```
   */
  static databasefailedToConnect001(
    parameters: Record<string, never>,
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('DB_001', parameters, metadata);
  }

  /**
   * Factory for DB_002: Database connection lost
   *
   * No parameters required
   *
   * @example
   * ```ts
   * throw Errors.databasedatabaseConnectionLost002({});
   * ```
   */
  static databasedatabaseConnectionLost002(
    parameters: Record<string, never>,
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('DB_002', parameters, metadata);
  }

  /**
   * Factory for DB_003: Record already exists: {$entity}
   *
   * @param parameters.entity - Entity type (optional)
   *
   * @example
   * ```ts
   * throw Errors.databaserecordAlreadyExists003({});
   * ```
   */
  static databaserecordAlreadyExists003(
    parameters: Partial<{
      entity?: string;
    }>,
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('DB_003', parameters, metadata);
  }

  /**
   * Factory for DB_004: Record not found in database
   *
   * @param parameters.entity - Entity type (optional)
   *
   * @example
   * ```ts
   * throw Errors.databaserecordNotFound004({});
   * ```
   */
  static databaserecordNotFound004(
    parameters: Partial<{
      entity?: string;
    }>,
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('DB_004', parameters, metadata);
  }

  /**
   * Factory for DB_005: Database query failed
   *
   * @param parameters.query - Query details (optional)
   *
   * @example
   * ```ts
   * throw Errors.databasedatabaseQueryFailed005({});
   * ```
   */
  static databasedatabaseQueryFailed005(
    parameters: Partial<{
      query?: string;
    }>,
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('DB_005', parameters, metadata);
  }

  /**
   * Factory for DB_006: Foreign key constraint violation
   *
   * @param parameters.constraint - Constraint name (optional)
   *
   * @example
   * ```ts
   * throw Errors.databaseforeignKeyConstraint006({});
   * ```
   */
  static databaseforeignKeyConstraint006(
    parameters: Partial<{
      constraint?: string;
    }>,
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('DB_006', parameters, metadata);
  }

  /**
   * Factory for DB_007: Database transaction failed
   *
   * No parameters required
   *
   * @example
   * ```ts
   * throw Errors.databasedatabaseTransactionFailed007({});
   * ```
   */
  static databasedatabaseTransactionFailed007(
    parameters: Record<string, never>,
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('DB_007', parameters, metadata);
  }

  /**
   * Factory for DB_008: Too many database connections
   *
   * No parameters required
   *
   * @example
   * ```ts
   * throw Errors.databasetooManyDatabase008({});
   * ```
   */
  static databasetooManyDatabase008(
    parameters: Record<string, never>,
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('DB_008', parameters, metadata);
  }

  /**
   * Factory for DB_009: Invalid query parameter: {$parameter}
   *
   * @param parameters.parameter - Invalid parameter
   *
   * @example
   * ```ts
   * throw Errors.databaseinvalidQueryParameter009({ parameter: 'example' });
   * ```
   */
  static databaseinvalidQueryParameter009(
    parameters: {
      parameter: string;
    },
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('DB_009', parameters, metadata);
  }

  /**
   * Factory for DB_010: Unique constraint violation
   *
   * @param parameters.field - Field name (optional)
   *
   * @example
   * ```ts
   * throw Errors.databaseuniqueConstraintViolation010({});
   * ```
   */
  static databaseuniqueConstraintViolation010(
    parameters: Partial<{
      field?: string;
    }>,
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('DB_010', parameters, metadata);
  }

  /**
   * Factory for EXT_001: Failed to connect to {$service}
   *
   * @param parameters.service - Service name
   *
   * @example
   * ```ts
   * throw Errors.externalfailedToConnect001({ service: 'example' });
   * ```
   */
  static externalfailedToConnect001(
    parameters: {
      service: string;
    },
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('EXT_001', parameters, metadata);
  }

  /**
   * Factory for EXT_002: {$service} returned an error: {$errorMessage}
   *
   * @param parameters.service - Service name
   * @param parameters.errorMessage - Error from service
   *
   * @example
   * ```ts
   * throw Errors.externalserviceReturnedAn002({ service: 'example', errorMessage: 'example' });
   * ```
   */
  static externalserviceReturnedAn002(
    parameters: {
      service: string;
      errorMessage: string;
    },
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('EXT_002', parameters, metadata);
  }

  /**
   * Factory for EXT_003: {$service} request timed out
   *
   * @param parameters.service - Service name
   *
   * @example
   * ```ts
   * throw Errors.externalserviceRequestTimed003({ service: 'example' });
   * ```
   */
  static externalserviceRequestTimed003(
    parameters: {
      service: string;
    },
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('EXT_003', parameters, metadata);
  }

  /**
   * Factory for EXT_004: Invalid API key for {$service}
   *
   * @param parameters.service - Service name
   *
   * @example
   * ```ts
   * throw Errors.externalinvalidApiKey004({ service: 'example' });
   * ```
   */
  static externalinvalidApiKey004(
    parameters: {
      service: string;
    },
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('EXT_004', parameters, metadata);
  }

  /**
   * Factory for EXT_005: Rate limit exceeded for {$service}. Retry after {$retryAfter} seconds
   *
   * @param parameters.service - Service name
   * @param parameters.retryAfter - Seconds to wait
   *
   * @example
   * ```ts
   * throw Errors.externalrateLimitExceeded005({ service: 'example', retryAfter: 123 });
   * ```
   */
  static externalrateLimitExceeded005(
    parameters: {
      service: string;
      retryAfter: number;
    },
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('EXT_005', parameters, metadata);
  }

  /**
   * Factory for EXT_006: {$service} is currently unavailable
   *
   * @param parameters.service - Service name
   *
   * @example
   * ```ts
   * throw Errors.externalserviceIsCurrently006({ service: 'example' });
   * ```
   */
  static externalserviceIsCurrently006(
    parameters: {
      service: string;
    },
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('EXT_006', parameters, metadata);
  }

  /**
   * Factory for EXT_007: Webhook delivery failed: {$reason}
   *
   * @param parameters.reason - Failure reason
   *
   * @example
   * ```ts
   * throw Errors.externalwebhookDeliveryFailed007({ reason: 'example' });
   * ```
   */
  static externalwebhookDeliveryFailed007(
    parameters: {
      reason: string;
    },
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('EXT_007', parameters, metadata);
  }

  /**
   * Factory for FILE_001: File upload failed: {$reason}
   *
   * @param parameters.reason - Failure reason
   *
   * @example
   * ```ts
   * throw Errors.filefileUploadFailed001({ reason: 'example' });
   * ```
   */
  static filefileUploadFailed001(
    parameters: {
      reason: string;
    },
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('FILE_001', parameters, metadata);
  }

  /**
   * Factory for FILE_002: Invalid file type: {$fileType}. Allowed types: {$allowedTypes}
   *
   * @param parameters.fileType - Uploaded file type
   * @param parameters.allowedTypes - Allowed file types
   *
   * @example
   * ```ts
   * throw Errors.fileinvalidFileType002({ fileType: 'example', allowedTypes: 'example' });
   * ```
   */
  static fileinvalidFileType002(
    parameters: {
      fileType: string;
      allowedTypes: string;
    },
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('FILE_002', parameters, metadata);
  }

  /**
   * Factory for FILE_003: File size {$size}MB exceeds maximum allowed size of {$maxSize}MB
   *
   * @param parameters.size - Uploaded file size
   * @param parameters.maxSize - Maximum file size
   *
   * @example
   * ```ts
   * throw Errors.filefileSizeSizemb003({ size: 123, maxSize: 123 });
   * ```
   */
  static filefileSizeSizemb003(
    parameters: {
      size: number;
      maxSize: number;
    },
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('FILE_003', parameters, metadata);
  }

  /**
   * Factory for FILE_004: File not found: {$filename}
   *
   * @param parameters.filename - File name
   *
   * @example
   * ```ts
   * throw Errors.filefileNotFound004({ filename: 'example' });
   * ```
   */
  static filefileNotFound004(
    parameters: {
      filename: string;
    },
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('FILE_004', parameters, metadata);
  }

  /**
   * Factory for FILE_005: Permission denied to access file: {$filename}
   *
   * @param parameters.filename - File name
   *
   * @example
   * ```ts
   * throw Errors.filepermissionDeniedTo005({ filename: 'example' });
   * ```
   */
  static filepermissionDeniedTo005(
    parameters: {
      filename: string;
    },
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('FILE_005', parameters, metadata);
  }

  /**
   * Factory for FILE_006: File storage error: {$reason}
   *
   * @param parameters.reason - Error details
   *
   * @example
   * ```ts
   * throw Errors.filefileStorageError006({ reason: 'example' });
   * ```
   */
  static filefileStorageError006(
    parameters: {
      reason: string;
    },
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('FILE_006', parameters, metadata);
  }

  /**
   * Factory for FILE_007: File corrupted or invalid: {$filename}
   *
   * @param parameters.filename - File name
   *
   * @example
   * ```ts
   * throw Errors.filefileCorruptedOr007({ filename: 'example' });
   * ```
   */
  static filefileCorruptedOr007(
    parameters: {
      filename: string;
    },
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('FILE_007', parameters, metadata);
  }

  /**
   * Factory for FILE_008: Insufficient storage space
   *
   * No parameters required
   *
   * @example
   * ```ts
   * throw Errors.fileinsufficientStorageSpace008({});
   * ```
   */
  static fileinsufficientStorageSpace008(
    parameters: Record<string, never>,
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('FILE_008', parameters, metadata);
  }

  /**
   * Factory for SYS_001: Internal server error
   *
   * No parameters required
   *
   * @example
   * ```ts
   * throw Errors.systeminternalServerError001({});
   * ```
   */
  static systeminternalServerError001(
    parameters: Record<string, never>,
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('SYS_001', parameters, metadata);
  }

  /**
   * Factory for SYS_002: Service temporarily unavailable
   *
   * No parameters required
   *
   * @example
   * ```ts
   * throw Errors.systemserviceTemporarilyUnavailable002({});
   * ```
   */
  static systemserviceTemporarilyUnavailable002(
    parameters: Record<string, never>,
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('SYS_002', parameters, metadata);
  }

  /**
   * Factory for SYS_003: Configuration error: {$configKey}
   *
   * @param parameters.configKey - Configuration key
   *
   * @example
   * ```ts
   * throw Errors.systemconfigurationErrorConfigkey003({ configKey: 'example' });
   * ```
   */
  static systemconfigurationErrorConfigkey003(
    parameters: {
      configKey: string;
    },
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('SYS_003', parameters, metadata);
  }

  /**
   * Factory for SYS_004: Feature {$feature} is not enabled
   *
   * @param parameters.feature - Feature name
   *
   * @example
   * ```ts
   * throw Errors.systemfeatureFeatureIs004({ feature: 'example' });
   * ```
   */
  static systemfeatureFeatureIs004(
    parameters: {
      feature: string;
    },
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('SYS_004', parameters, metadata);
  }

  /**
   * Factory for SYS_005: Rate limit exceeded. Try again in {$retryAfter} seconds
   *
   * @param parameters.retryAfter - Seconds to wait
   *
   * @example
   * ```ts
   * throw Errors.systemrateLimitExceeded005({ retryAfter: 123 });
   * ```
   */
  static systemrateLimitExceeded005(
    parameters: {
      retryAfter: number;
    },
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('SYS_005', parameters, metadata);
  }

  /**
   * Factory for SYS_006: Cache service error
   *
   * No parameters required
   *
   * @example
   * ```ts
   * throw Errors.systemcacheServiceError006({});
   * ```
   */
  static systemcacheServiceError006(
    parameters: Record<string, never>,
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('SYS_006', parameters, metadata);
  }

  /**
   * Factory for SYS_007: Job processing failed: {$jobType}
   *
   * @param parameters.jobType - Job type
   *
   * @example
   * ```ts
   * throw Errors.systemjobProcessingFailed007({ jobType: 'example' });
   * ```
   */
  static systemjobProcessingFailed007(
    parameters: {
      jobType: string;
    },
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('SYS_007', parameters, metadata);
  }

  /**
   * Factory for SYS_008: Message queue error
   *
   * No parameters required
   *
   * @example
   * ```ts
   * throw Errors.systemmessageQueueError008({});
   * ```
   */
  static systemmessageQueueError008(
    parameters: Record<string, never>,
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('SYS_008', parameters, metadata);
  }

  /**
   * Factory for SYS_009: Email sending failed
   *
   * No parameters required
   *
   * @example
   * ```ts
   * throw Errors.systememailSendingFailed009({});
   * ```
   */
  static systememailSendingFailed009(
    parameters: Record<string, never>,
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('SYS_009', parameters, metadata);
  }

  /**
   * Factory for SYS_010: Scheduler error: {$task}
   *
   * @param parameters.task - Scheduled task
   *
   * @example
   * ```ts
   * throw Errors.systemschedulerErrorTask010({ task: 'example' });
   * ```
   */
  static systemschedulerErrorTask010(
    parameters: {
      task: string;
    },
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('SYS_010', parameters, metadata);
  }

  /**
   * Factory for USER_001: User with ID {$userId} not found
   *
   * @param parameters.userId - User ID
   *
   * @example
   * ```ts
   * throw Errors.useruserWithId001({ userId: 'example' });
   * ```
   */
  static useruserWithId001(
    parameters: {
      userId: string;
    },
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('USER_001', parameters, metadata);
  }

  /**
   * Factory for USER_002: User with email {$email} already exists
   *
   * @param parameters.email - User email
   *
   * @example
   * ```ts
   * throw Errors.useruserWithEmail002({ email: 'example' });
   * ```
   */
  static useruserWithEmail002(
    parameters: {
      email: string;
    },
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('USER_002', parameters, metadata);
  }

  /**
   * Factory for USER_003: Invalid email format: {$email}
   *
   * @param parameters.email - Invalid email
   *
   * @example
   * ```ts
   * throw Errors.userinvalidEmailFormat003({ email: 'example' });
   * ```
   */
  static userinvalidEmailFormat003(
    parameters: {
      email: string;
    },
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('USER_003', parameters, metadata);
  }

  /**
   * Factory for USER_004: Password does not meet security requirements
   *
   * No parameters required
   *
   * @example
   * ```ts
   * throw Errors.userpasswordDoesNot004({});
   * ```
   */
  static userpasswordDoesNot004(
    parameters: Record<string, never>,
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('USER_004', parameters, metadata);
  }

  /**
   * Factory for USER_005: Passwords do not match
   *
   * No parameters required
   *
   * @example
   * ```ts
   * throw Errors.userpasswordsDoNot005({});
   * ```
   */
  static userpasswordsDoNot005(
    parameters: Record<string, never>,
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('USER_005', parameters, metadata);
  }

  /**
   * Factory for USER_006: User account is disabled
   *
   * No parameters required
   *
   * @example
   * ```ts
   * throw Errors.useruserAccountIs006({});
   * ```
   */
  static useruserAccountIs006(
    parameters: Record<string, never>,
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('USER_006', parameters, metadata);
  }

  /**
   * Factory for USER_007: User account is suspended: {$reason}
   *
   * @param parameters.reason - Suspension reason (optional)
   *
   * @example
   * ```ts
   * throw Errors.useruserAccountIs007({});
   * ```
   */
  static useruserAccountIs007(
    parameters: Partial<{
      reason?: string;
    }>,
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('USER_007', parameters, metadata);
  }

  /**
   * Factory for USER_008: Invalid phone number format: {$phone}
   *
   * @param parameters.phone - Phone number
   *
   * @example
   * ```ts
   * throw Errors.userinvalidPhoneNumber008({ phone: 'example' });
   * ```
   */
  static userinvalidPhoneNumber008(
    parameters: {
      phone: string;
    },
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('USER_008', parameters, metadata);
  }

  /**
   * Factory for USER_009: Profile image size exceeds maximum allowed size of {$maxSize}MB
   *
   * @param parameters.maxSize - Maximum size in MB
   *
   * @example
   * ```ts
   * throw Errors.userprofileImageSize009({ maxSize: 123 });
   * ```
   */
  static userprofileImageSize009(
    parameters: {
      maxSize: number;
    },
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('USER_009', parameters, metadata);
  }

  /**
   * Factory for USER_010: Cannot delete your own account
   *
   * No parameters required
   *
   * @example
   * ```ts
   * throw Errors.usercannotDeleteYour010({});
   * ```
   */
  static usercannotDeleteYour010(
    parameters: Record<string, never>,
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('USER_010', parameters, metadata);
  }

  /**
   * Factory for VAL_001: Validation failed: {$field} is required
   *
   * @param parameters.field - Field name
   *
   * @example
   * ```ts
   * throw Errors.validationvalidationFailedField001({ field: 'example' });
   * ```
   */
  static validationvalidationFailedField001(
    parameters: {
      field: string;
    },
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('VAL_001', parameters, metadata);
  }

  /**
   * Factory for VAL_002: Invalid value for {$field}: expected {$expectedType}
   *
   * @param parameters.field - Field name
   * @param parameters.expectedType - Expected type
   *
   * @example
   * ```ts
   * throw Errors.validationinvalidValueFor002({ field: 'example', expectedType: 'example' });
   * ```
   */
  static validationinvalidValueFor002(
    parameters: {
      field: string;
      expectedType: string;
    },
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('VAL_002', parameters, metadata);
  }

  /**
   * Factory for VAL_003: Value for {$field} must be between {$min} and {$max}
   *
   * @param parameters.field - Field name
   * @param parameters.min - Minimum value
   * @param parameters.max - Maximum value
   *
   * @example
   * ```ts
   * throw Errors.validationvalueForField003({ field: 'example', min: 123, max: 123 });
   * ```
   */
  static validationvalueForField003(
    parameters: {
      field: string;
      min: number;
      max: number;
    },
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('VAL_003', parameters, metadata);
  }

  /**
   * Factory for VAL_004: Text for {$field} must be between {$minLength} and {$maxLength} characters
   *
   * @param parameters.field - Field name
   * @param parameters.minLength - Minimum length
   * @param parameters.maxLength - Maximum length
   *
   * @example
   * ```ts
   * throw Errors.validationtextForField004({ field: 'example', minLength: 123, maxLength: 123 });
   * ```
   */
  static validationtextForField004(
    parameters: {
      field: string;
      minLength: number;
      maxLength: number;
    },
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('VAL_004', parameters, metadata);
  }

  /**
   * Factory for VAL_005: Invalid UUID format: {$value}
   *
   * @param parameters.value - Invalid UUID
   *
   * @example
   * ```ts
   * throw Errors.validationinvalidUuidFormat005({ value: 'example' });
   * ```
   */
  static validationinvalidUuidFormat005(
    parameters: {
      value: string;
    },
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('VAL_005', parameters, metadata);
  }

  /**
   * Factory for VAL_006: Invalid date format: {$date}. Expected format: {$expectedFormat}
   *
   * @param parameters.date - Invalid date
   * @param parameters.expectedFormat - Expected format
   *
   * @example
   * ```ts
   * throw Errors.validationinvalidDateFormat006({ date: 'example', expectedFormat: 'example' });
   * ```
   */
  static validationinvalidDateFormat006(
    parameters: {
      date: string;
      expectedFormat: string;
    },
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('VAL_006', parameters, metadata);
  }

  /**
   * Factory for VAL_007: Invalid URL format: {$url}
   *
   * @param parameters.url - Invalid URL
   *
   * @example
   * ```ts
   * throw Errors.validationinvalidUrlFormat007({ url: 'example' });
   * ```
   */
  static validationinvalidUrlFormat007(
    parameters: {
      url: string;
    },
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('VAL_007', parameters, metadata);
  }

  /**
   * Factory for VAL_008: Date {$field} must be in the future
   *
   * @param parameters.field - Field name
   *
   * @example
   * ```ts
   * throw Errors.validationdateFieldMust008({ field: 'example' });
   * ```
   */
  static validationdateFieldMust008(
    parameters: {
      field: string;
    },
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('VAL_008', parameters, metadata);
  }

  /**
   * Factory for VAL_009: Date {$field} must be in the past
   *
   * @param parameters.field - Field name
   *
   * @example
   * ```ts
   * throw Errors.validationdateFieldMust009({ field: 'example' });
   * ```
   */
  static validationdateFieldMust009(
    parameters: {
      field: string;
    },
    metadata?: import('../registry/error-registry.types').ErrorMetadata
  ): RegisteredError {
    return new RegisteredError('VAL_009', parameters, metadata);
  }
}
