export const STORAGE_PROVIDER_TOKEN = 'STORAGE_PROVIDER_TOKEN';
export const STORAGE_MODULE_OPTIONS = 'STORAGE_MODULE_OPTIONS';
export const STORAGE_PROVIDER_MAP_TOKEN = 'STORAGE_PROVIDER_MAP_TOKEN';
export const STORAGE_REGISTRY_TOKEN = 'STORAGE_REGISTRY_TOKEN';
