/**
 * Error registry definitions compilation
 *
 * This module imports all domain-specific error definitions
 * and compiles them into a single ERROR_REGISTRY constant.
 */

import { AUTH_ERRORS } from './auth.errors';
import { BUSINESS_ERRORS } from './business.errors';
import { DATABASE_ERRORS } from './database.errors';
import { EXTERNAL_ERRORS } from './external.errors';
import { FILE_ERRORS } from './file.errors';
import { SYSTEM_ERRORS } from './system.errors';
import { USER_ERRORS } from './user.errors';
import { VALIDATION_ERRORS } from './validation.errors';
import { deepFreeze } from '../../utils/deep-freeze';

import type { ErrorCode, ErrorDefinition, ErrorRegistryMap } from '../error-registry.types';

/**
 * Complete error registry containing all error definitions
 *
 * This is the single source of truth for all error codes in the system.
 * Each error is uniquely identified by its code and contains complete metadata.
 *
 * @example
 * ```ts
 * import { ERROR_REGISTRY } from '@package/errors';
 *
 * const userNotFound = ERROR_REGISTRY['USER_001'];
 * console.log(userNotFound.message); // "User with ID {userId} not found"
 * ```
 */
export const ERROR_REGISTRY: ErrorRegistryMap = deepFreeze(
  Object.fromEntries(
    [
      ...USER_ERRORS,
      ...AUTH_ERRORS,
      ...VALIDATION_ERRORS,
      ...DATABASE_ERRORS,
      ...BUSINESS_ERRORS,
      ...EXTERNAL_ERRORS,
      ...FILE_ERRORS,
      ...SYSTEM_ERRORS
    ].map((error) => [error.code, error])
  )
) as ErrorRegistryMap;

/**
 * Re-export ErrorCode union type from error-registry.types.ts
 * (auto-generated by generate-types.ts)
 */
export type { ErrorCode } from '../error-registry.types';

/**
 * Get error definition by code
 *
 * @param code - Error code to look up
 * @returns Error definition or undefined if not found
 *
 * @example
 * ```ts
 * const def = getErrorDefinition('USER_001');
 * if (def) {
 *   console.log(def.message);
 * }
 * ```
 */
export function getErrorDefinition(code: string): ErrorDefinition | undefined {
  return ERROR_REGISTRY[code];
}

/**
 * Check if an error code exists in the registry
 *
 * @param code - Error code to check
 * @returns True if error code exists
 *
 * @example
 * ```ts
 * if (isErrorCode('USER_001')) {
 *   // Handle known error
 * }
 * ```
 */
export function isErrorCode(code: string): code is ErrorCode {
  return code in ERROR_REGISTRY;
}

/**
 * Get all error codes for a specific type/domain
 *
 * @param type - Error type to filter by
 * @returns Array of error codes for the type
 *
 * @example
 * ```ts
 * const userErrors = getErrorCodesByType(ErrorType.USER);
 * // Returns ['USER_001', 'USER_002', ...]
 * ```
 */
export function getErrorCodesByType(type: string): ErrorCode[] {
  return Object.values(ERROR_REGISTRY)
    .filter((error) => error.type === type)
    .map((error) => error.code as ErrorCode);
}

/**
 * Validates a single parameter value against its type
 *
 * @param value - The value to validate
 * @param type - The expected type
 * @returns True if the value matches the type
 */
function validateParameterValue(value: unknown, type: string): boolean {
  switch (type) {
    case 'string':
      return typeof value === 'string';
    case 'number':
      return typeof value === 'number' && !isNaN(value);
    case 'boolean':
      return typeof value === 'boolean';
    case 'date':
      if (value instanceof Date) {
        return !isNaN(value.getTime());
      }
      return typeof value === 'string' && !isNaN(Date.parse(value));
    case 'object':
      return typeof value === 'object' && value !== null;
    default:
      return false;
  }
}

/**
 * Validate error parameters against definition
 *
 * @param code - Error code
 * @param parameters - Provided parameters
 * @returns Validation result with any missing required parameters
 *
 * @example
 * ```ts
 * const result = validateErrorParameters('USER_001', { userId: '123' });
 * if (!result.valid) {
 *   console.error('Missing params:', result.missing);
 * }
 * ```
 */
export function validateErrorParameters(
  code: string,
  parameters: Record<string, unknown>
): { valid: boolean; missing: string[]; invalid: string[] } {
  const definition = ERROR_REGISTRY[code];
  if (!definition || !definition.parameters) {
    return { valid: true, missing: [], invalid: [] };
  }

  const missing: string[] = [];
  const invalid: string[] = [];

  for (const param of definition.parameters) {
    const value = parameters[param.name];

    // Check if required parameter is missing
    // Note: We check explicitly for undefined to handle case where optional param
    // is set to undefined vs not being provided at all
    if (param.required && (value === undefined || !(param.name in parameters))) {
      missing.push(param.name);
      continue;
    }

    // If parameter exists and is not undefined, validate its type
    // Optional parameters can be undefined without being invalid
    if (param.name in parameters && value !== undefined) {
      if (!validateParameterValue(value, param.type)) {
        invalid.push(param.name);
      }
    }
  }

  return { valid: missing.length === 0 && invalid.length === 0, missing, invalid };
}

// Export all error definition arrays for reference
export {
  USER_ERRORS,
  AUTH_ERRORS,
  VALIDATION_ERRORS,
  DATABASE_ERRORS,
  BUSINESS_ERRORS,
  EXTERNAL_ERRORS,
  FILE_ERRORS,
  SYSTEM_ERRORS
};
